NetCommons3/Questionnaires

- Test/Case/AllQuestionnairesTest.php
- phpunit.xml.dist
https://github.com/NetCommons3/NetCommons3/issues/28
とりあえずphpunitテストは通らないように修正しています。
> phpunit.xml.distの修正

- Model/QuestionnaireFrameSetting.php
> Fix sort direction

- Controller/QuestionnaireBlockRolePermissionsController.php
- Controller/QuestionnaireBlocksController.php
- Controller/QuestionnaireFrameSettingsController.php
- View/QuestionnaireBlockRolePermissions/edit.ctp
- View/QuestionnaireBlocks/index.ctp
- View/QuestionnaireBlocks/not_found.ctp
- View/QuestionnaireFrameSettings/edit.ctp
https://github.com/NetCommons3/Blocks/issues/14
> BlockTabsComponentからBlockTabsHelperに変更

- Config/Migration/002_mail_setting_records.php
https://github.com/NetCommons3/Mails/issues/60
> MailSettingテーブルの定型文だけ別テーブルに切り出し

- Config/Migration/002_mail_setting_records.php
- Controller/QuestionnaireMailSettingsController.php
- View/QuestionnaireMailSettings/edit.ctp
https://github.com/NetCommons3/Mails/issues/79
> メール設定多段見直し

- View/QuestionnaireMailSettings/edit.ctp
https://github.com/NetCommons3/Mails/issues/84
> 問合せ先メールアドレス表示

- Config/Migration/002_mail_setting_records.php
https://github.com/NetCommons3/Mails/issues/86
> メールDB項目 承認メール通知機能を使う 追加対応 

- Controller/QuestionnaireEditController.php
https://github.com/NetCommons3/NetCommons3/issues/88
> 「$this->request->isPost(); // 非推奨」の修正

- Test/Case/Model/Questionnaires/SaveQuestionnaireTest.php
blockSetting共通化対応でテスト漏れがあったので、プルリクエスト送ります。
> テスト修正 - Model/Questionnaires/SaveQuestionnaireTest

- Model/QuestionnaireSetting.php
https://github.com/NetCommons3/NetCommons3/issues/320
トラビスOKで、小テスト、アンケートをマージしましたら、お手数ですがissueクローズお願いします。
> プラグイン配置できない不具合対応 - blockSetting共通化対応

- Model/QuestionnaireSetting.php
> pluginKeyの直書き指定不要になった - blockSetting共通化対応

- Config/Migration/001_plugin_records.php
- Test/Case/Controller/QuestionnaireAddController/AddTest.php
- Test/Case/Controller/QuestionnaireEditController/DeleteTest.php
- Test/Case/Controller/QuestionnaireEditController/EditQuestionTest.php
- Test/Case/Controller/QuestionnaireEditController/EditResultTest.php
- Test/Case/Controller/QuestionnaireEditController/EditTest.php
- Test/Case/Model/QuestionnairePage/GetNextPageTest.php
- Test/Case/Model/QuestionnaireSetting/SaveBlockTest.php
- Test/Case/Model/Questionnaires/AfterFrameSaveTest.php
- Test/Case/Model/Questionnaires/SaveQuestionnaireTest.php
ボックスの変更機能の追加
https://github.com/NetCommons3/NetCommons3/issues/726
https://github.com/NetCommons3/NetCommons3/issues/564
> ボックスの変更機能の追加

- Config/Migration/001_plugin_records.php
- Config/Migration/1450753185_init.php
- Config/Schema/schema.php
- Test/Fixture/QuestionnaireFixture.php
https://github.com/NetCommons3/NetCommons3/issues/726
> Boxの切り替え機能の再修正

- webroot/js/questionnaires_edit_question.js
https://github.com/NetCommons3/NetCommons3/issues/778
> AngularJS 1.6対応

- Test/Case/Controller/QuestionnaireEditController/EditTest.php
- View/Elements/ng_status_label.ctp
- View/Helper/QuestionnaireStatusLabelHelper.php
https://github.com/NetCommons3/NetCommons3/issues/112
> Workflowの状態定数名変更

- Config/Migration/001_plugin_records.php
- Config/Migration/1484546423_add_is_original_copy.php
- Config/Schema/schema.php
- TestSuite/QuestionnairesSaveTest.php
https://github.com/NetCommons3/NetCommons3/issues/770
> 多言語化対応（is_original_copyフィールド追加）

- Test/Case/Controller/QuestionnaireBlocksController/DownloadTest.php
- Test/Case/Controller/QuestionnaireBlocksController/ExportTest.php
- TestSuite/QuestionnaireAnswerValidateTest.php
- TestSuite/QuestionnairesSaveTest.php
https://github.com/NetCommons3/NetCommons3/issues/998
> generateNcの後にログイン処理をするように修正

- Controller/QuestionnaireAddController.php
- Controller/QuestionnaireAnswerSummariesController.php
- Controller/QuestionnaireAnswersController.php
- Controller/QuestionnaireBlocksController.php
- Controller/QuestionnaireEditController.php
- Controller/QuestionnairesController.php
bugfixです。
トラビステストが終わったら、マージしようと思ってます。
https://github.com/NetCommons3/NetCommons3/issues/1213
> fix: App::uses()の参照先修正

- Controller/QuestionnaireEditController.php
- View/QuestionnaireEdit/edit.ctp
- View/QuestionnaireEdit/edit_question.ctp
- View/QuestionnaireEdit/edit_result.ctp
refs https://github.com/NetCommons3/NetCommons3/issues/923
> セッティングモードにある編集画面なのにブロック設定などのタブメニューが出ないに対応

- Controller/QuestionnaireAddController.php
https://github.com/NetCommons3/NetCommons3/issues/1298
> 存在しないモデルを指定していたため削除

- Model/QuestionnaireAnswerSummaryCsv.php
- Test/Case/Controller/QuestionnaireBlockRolePermissionsController/EditTest.php
https://github.com/NetCommons3/NetCommons3/issues/1491
バグ修正のプルリクエストです。
トラビステスト通ったら、マージしようと思ってます。
動作確認済みです。
> fix: アンケート、回答ダウンロード時に回答日の時間が9時間ズレるのを修正

- Controller/QuestionnaireEditController.php
- View/QuestionnaireEdit/edit.ctp
https://github.com/NetCommons3/Registrations/pull/66 と同様の変更をアンケートにも行いました。
> change: 「メール通知機能を使う」がOffでも回答の「メール配信設定」を変更できるようにした
